# Generated by Django 4.2.11 on 2024-03-08 08:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('apartment_number', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('free', 'free'), ('rented', 'rented'), ('booked', 'booked'), ('renovation', 'renovation')], max_length=20)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('cleaner_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('passport_number', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('apartment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apart_number', to='hotel.apartments')),
                ('passport_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_passport', to='hotel.guest')),
            ],
        ),
        migrations.CreateModel(
            name='CleanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('пн', 'пн'), ('вт', 'вт'), ('ср', 'ср'), ('чт', 'чт'), ('пт', 'пт'), ('сб', 'сб'), ('вс', 'вс')], max_length=10)),
                ('cleaner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sch_cleaner_id', to='hotel.cleaner')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sch_floor', to='hotel.floor')),
            ],
        ),
        migrations.AddField(
            model_name='apartments',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apart_number', to='hotel.floor'),
        ),
    ]
