site_name: Tigran Kazaryan

theme:
  locale: ru
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

nav:
 - Лабораторная 1:
     - Задание 1: lab1/1
     - Задание 2: lab1/2
     - Задание 3: lab1/3
     - Задание 4: lab1/4
     - Задание 5: lab1/5
 - Лабораторная 2:
     - Введение: lab2/main
     - Модели: lab2/models
     - Запросы: lab2/views
 - Лабораторная 3:
     - Лабораторная работа 3: lab3/lab3
 - Лабораторная 4:
     - Лабораторная работа 4: lab4/lab4