# Generated by Django 5.1.6 on 2025-03-24 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworksubmission',
            options={'verbose_name': 'Ответ на задание', 'verbose_name_plural': 'Ответы на задания'},
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='answer',
            field=models.TextField(verbose_name='Ответ студента'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homework', verbose_name='Домашнее задание'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='is_graded',
            field=models.BooleanField(default=False, verbose_name='Оценено'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки'),
        ),
        migrations.AlterUniqueTogether(
            name='homeworksubmission',
            unique_together={('student', 'homework')},
        ),
        migrations.DeleteModel(
            name='SubmittedHomework',
        ),
    ]
