# Generated by Django 5.1.6 on 2025-03-24 12:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_homeworksubmission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworksubmission',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='homeworksubmission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homework'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SubmittedHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Ответ')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата сдачи')),
                ('is_accepted', models.BooleanField(default=False)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.homework', verbose_name='Задание')),
                ('student', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'unique_together': {('student', 'homework')},
            },
        ),
    ]
